name: E2E Tests
on: push
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: yarn
    - name: Run e2e tests
      run: yarn test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15